# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  hashiUrl: https://hexadic-unridered-tasia.ngrok-free.dev
  roleName: gha-test-role
  audience: https://github.com/murugcp
 # namespace: cicd
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
        contents: read
        id-token: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: perform token run
        run: |
         echo $(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://github.com/murugcp")
        shell: bash
      - name: Retreive Secrets
        id: retrieve-secrets
        uses: hashicorp/vault-action@v3.4.0
        with:
         url: ${{ env.hashiUrl }}
         role: ${{ env.roleName }}
         method: jwt
         jwtGithubAudience: ${{ env.audience }}
         #namespace: ${{ env.namespace }}
         tlsSkipVerify: true
         exportEnv: true
         secrets: |
           secret/data/apikeys deploymentServer | DEPLOYMENT_KEY





        
